name: Trigger Build 

on:
  push:
    branches:
      - main

jobs:
  trigger-blog-core:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

     